# Generated by Django 4.0.4 on 2022-04-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=250)),
                ('price', models.FloatField()),
                ('series', models.CharField(max_length=200)),
            ],
        ),
    ]
